# Dockerfile.local

FROM node:18-alpine AS build

# Mimic local environment by disabling CI mode
ENV CI=false

# Set working directory
WORKDIR /app

# Copy the entire repository so that the client folder is present
COPY . .

# Install dependencies (this runs the postinstall script)
RUN npm install --legacy-peer-deps --verbose && npm cache clean --force

# Expose the application port
EXPOSE 8080

# Start the application
CMD ["npm", "start"]
